### ISSUE TITLE
Add support for ignoring certain global variables

### ISSUE THREAD

**Issue by brocococonut** [PerimeterX/restringer#2]
For things like malware or extremely obfuscated extensions, restringer seems to fail on things like the `chrome` object.
I propose adding in a flag (or option) to handle those types of object (`chrome`, `browser`, etc.) - or rather,t o ignore them and treat them as predefined objects in the global scope.

**Comment by BenBaryoPX** [comment]
That sounds doable. Can you provide a code example of such a script?

**Comment by brocococonut** [comment]
Absolutely I can!
I'll provide an obfuscated example, as well as a real-world (somewhat dodgy) obfuscated chrome extension example.
Here's the hello_world example from the chrome-

**Comment by brocococonut** [comment]
One way keys for potentially undefined objects could be represented is using optional chaining. So converting it to something like `chrome?.runtime?...`
The downside with this is that it might get stripped as unreachable or `always false` code false positives depending on how things are done at the moment

**Comment by BenBaryoPX** [comment]
I've reviewed the code you added and seen the error you're talking about. 
The thing is, the error doesn't indicate a failure in deobfuscation. In fact, the script was completely deobfuscated, but an error was printed after the program finished its run. 

I'm now catching async errors, so the issue should be resolved.
Thanks for bringing this to my attention!
Closing this as fixed in v1.0.2
